### ISSUE TITLE
UnboundLocalError: local variable 'auth' referenced before assignment

### ISSUE THREAD

**Issue by swati1mehra** [openbaton/juju-charm#3]
Hi

Setup:
I have an up and running Openbaton release 3.2.0 on ubuntu server.
I followed steps for zabbix server 3.0 installation and configuration on ubuntu 14.04
My **zabbix dashboard** is reachable at http://your-ip/zabbix/actionconf.php 

*I got the helper script from wget https://raw.githubusercontent.com/openbaton/juju-charm/develop/hooks/zbx_helper.py

Issue : Configuration of the auto registration using the provided helper script FAILS.
Please see the error below -

root@ubuntu:/home/ubuntu# python zbx_helper.py -a
Error on connection to zabbix:()
Traceback (most recent call last):
  File "zbx_helper.py", line 346, in <module>
    main()
  File "zbx_helper.py", line 340, in main
    zbx_add_autoregistration(zbxurl, auth)
UnboundLocalError: local variable 'auth' referenced before assignment

**Comment by ranzpirat** [comment]
Have you tried `python zbx_helper.py -a -z $IP_OF_ZABBIX_SERVER`
"The error on connection to zabbix" tells that the initial retrieval of the auth-token fails.
Are you using the default username/password combo (Admin, zabbix) for testing? If you configured your zabbix server otherwise please provide them via `-u $USERNAME -p $PASSWORD` arguments.

Hope that helps!

**Comment by ranzpirat** [comment]
If you have further questions or problems running the charm, we can reopen the issue. Will close till then.
